name: Build-A-PC CI/CD Pipeline

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install hadolint (Dockerfile linter)
        run: |
          wget -qO /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Lint all Dockerfiles
        run: |
          find . -name Dockerfile -exec hadolint {} \;

      - name: Build and push backend image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"
          IMAGE_NAME="kerimkapetanovic/backend:${SHORT_SHA}"
          docker build -t "$IMAGE_NAME" ./backend
          docker push "$IMAGE_NAME"

      - name: Build and push frontend image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"
          IMAGE_NAME="kerimkapetanovic/build-a-pc:${SHORT_SHA}"
          docker build -t "$IMAGE_NAME" ./build-a-pc
          docker push "$IMAGE_NAME"

      - name: Build and push postgres image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"
          IMAGE_NAME="kerimkapetanovic/postgres:${SHORT_SHA}"
          docker build -t "$IMAGE_NAME" ./postgres
          docker push "$IMAGE_NAME"
